### ISSUE TITLE
Add possibility to create a filter with groups

### ISSUE THREAD

**Issue by KeremBalci111** [DLR-SC/ESID#102]
The website user should be able to create a filter that aggregates and/or disaggregates groups. The resulting filter should then be applied to all scenarios.

Example filter: 
  Age-group: [20-30, 30-50]
  Sex: [Female, Male]

Tasks:
- create the design of the filter editor.  Done

- create/update the API requests (currently there is no data for groups).

**Comment by kerklohlaurin** [comment]
closed on branch groupAggregation
