### ISSUE TITLE
Enhancement of Scenario Cards

### ISSUE THREAD

**Issue by PawanKaur** [DLR-SC/ESID#147]
To make scenario card  more visually appealing and the values more intuitive.  Which one is preferred? With arrows or with colors?

![scenario_card enhancement](https://user-images.githubusercontent.com/6088553/178575574-85dee960-9112-4bcc-9aad-f2b73746eab6.PNG)

Or some other icons that goes well with the semantics of positive and negative values for each compartments.

PS the idea is taken from stock exchange cards. For example boerse-berlin or lse

**Comment by JonasGilg** [comment]
I like the left one more. The color should be handled with a flag from the backend.

**Comment by PawanKaur** [comment]
There are problems of showing the arrows with the Recovered compartment.

**Comment by PawanKaur** [comment]
For some compartments the startValue (which is RKI value) are 0. Therefore, thee is no compartmentRate. Due to which it is showing as N/A. How to deal with this issue?  So how to decide + (value upwards), -(value downwards) or stagnate in this case when there is no comparative values.  Shall I use another symbol to show no comparison specially for these cases?
