### ISSUE TITLE
[GroupFilters] translate filter checkbox text

### ISSUE THREAD

**Issue by KeremBalci111** [DLR-SC/ESID#158]
add localization to Group Filters Component

**Comment by NXXR** [comment]
This needs to be changed in the backend.
See #204.

**Comment by KleinAn** [comment]
Can you change or translate "non-binary" to "divers" in the group administration? @JonasGilg

**Comment by JonasGilg** [comment]
> Can you change or translate "non-binary" to "divers" in the group administration? @JonasGilg

As the biological gender is meant we probably should change it to "intersex". We also should change the group title to "biological gender" or "biological sex" to make that more clear.

**Comment by KleinAn** [comment]
Will the incoming data have the same classification of "biological gender"? We are not sure about the data from the LHAs if its the case.

**Comment by JonasGilg** [comment]
Maybe this is something to ask the LHAs. But my intuition tells me, that health related data works with biological gender.

**Comment by lenarothenhaeusler** [comment]
@JonasGilg in Sormas for example the gender of cases was not specifically reported as biological gender

![Image](https://user-images.githubusercontent.com/125039884/231749244-c07f2513-81a6-4960-9a34-2b16e137b2f3.jpg)
