### ISSUE TITLE
Api does not return data for in some cases

### ISSUE THREAD

**Issue by lucaspataro** [DLR-SC/ESID#170]
Kerem found a situation where no data was send back to the client. 
I investigated a little and think there should have been data, so a deeper look needs to be taken.

Group filter:
- Select age groups 1 to 6
- Select gender 'female'

For Node 00000 (Germany) the Api does not return any data on Simulation 1, but in the database there actually is data for that setup!

SQL Query to check:
```
SELECT NODE_ID,
	NODE_NAME,
	DAY,
	GROUPS
FROM API_SIMULATIONDATA
WHERE SIMULATIONNODE_ID in
		(SELECT SIMULATIONNODE_ID
			FROM API_SIMULATION_NODES
			WHERE SIMULATION_ID = 1)
	AND NODE_NAME = '00000'
	AND (GROUPS ~ '^([^,]*,)*female(,[^,]*)*$'
						AND (GROUPS ~ '^([^,]*,)*age_0(,[^,]*)*$'
											OR GROUPS ~ '^([^,]*,)*age_1(,[^,]*)*$'
											OR GROUPS ~ '^([^,]*,)*age_2(,[^,]*)*$'
											OR GROUPS ~ '^([^,]*,)*age_3(,[^,]*)*$'
											OR GROUPS ~ '^([^,]*,)*age_4(,[^,]*)*$'
											OR GROUPS ~ '^([^,]*,)*age_5(,[^,]*)*$'))
ORDER BY NODE_NAME, day, groups
```

**Comment by kerklohlaurin** [comment]
I tried the exact case and i got data back, so i don't think there is an issue.
