### ISSUE TITLE
[Feedback]: German translations (for scenarios & compartments etc.) & Ability to rename Scenarios

### ISSUE THREAD

**Issue by NXXR** [DLR-SC/ESID#204]
### Feedback

German translations (for scenarios & compartments etc.) & Ability to rename Scenarios.

_Depends on work by HPC._

---
**_Related Issues:_**
- #158

**Comment by JonasGilg** [comment]
We need to temporarily hack translations for backend data into the frontend. This has the highest priority.

An idea is that we can also use [crowdin](https://crowdin.com/) for translations that are missing.

**Comment by NXXR** [comment]
Haven't used that yet. Maybe we can have a meeting to discuss the possible options?

I think we might also be able to use the existing translations via the json files even though it means the translated compartments would be hardcoded for now.

Depending on the implementation it might be easy for everyone to quickly push translation changes into the development build.

**Comment by NXXR** [comment]
We might as well define an API endpoint in the frontend and just generate the translations in there with the help of some translation system similar to the generator I used for the migrations during the coding week.

This way we can easily remove it later and fall back onto the API once the funcionalities are in place while already using the proper channels in the frontend.
