### ISSUE TITLE
Case Data still off by one day

### ISSUE THREAD

**Issue by NXXR** [DLR-SC/ESID#322]
According to Frederik there is still an offset in the date of the displayed case data.
e.g. ESID shows 2023-11-19 as the last date of data (the api also has this as the last date of the result).
but according to the metadata of the files uploaded by airflow it should be 2023-11-20.

We may need to investigate whether this is an issue of the upload to the database or if there is an issue when generating the response for the api request.

**Comment by JonasGilg** [comment]
I think this has been resolved. The issue wasn't in this repo, but rather in an internal pipeline.
