### ISSUE TITLE
Heat Legend Previews not showing

### ISSUE THREAD

**Issue by NXXR** [DLR-SC/ESID#326]
The het legend previews in the dropdown menu to select a preset seem to not render properly.

The Option Items are blank **until _after_ a preset is clicked on**.
![grafik](https://github.com/DLR-SC/ESID/assets/25636783/ab18decb-803b-4146-b226-d75a3831b0a9)

**Comment by shami-sneha** [comment]
Issue resolved ..... now Heat lagend previews is showing ....
![color](https://github.com/DLR-SC/ESID/assets/131749075/027e2a81-978e-4bb3-ad82-d51b4df33ed9)

**Comment by NXXR** [comment]
Nice,
can you create a PR for it so we can take a look at it and merge it into the develop branch?
remember to mention the issue in your PR description so github links them.
