### ISSUE TITLE
Reset/recenter district map when zooming back out

### ISSUE THREAD

**Issue by NXXR** [DLR-SC/ESID#92]
Add functionality to recenter district map when zooming back out to default zoom level.

AmCharts 5 provides `chart.goHome()` function to return to the initial view of the map (default zoom level and map position)

Add function to an event detecting zooming out & hitting default zoom level `0` and recentering the map.
Optionally, test out returning to default view on clicking the backround as described in [amCharts 5 documentation](https://www.amcharts.com/docs/v5/charts/map-chart/map-pan-zoom/#Via_background_click)

```typescript
chart.chartContainer.get('background')?.events.on('click', () => {
  console.log('Map BG clicked');
   chart.goHome();
});
```

**Comment by PawanKaur** [comment]
is issue#98 not the same.

**Comment by NXXR** [comment]
https://gist.github.com/NXXR/5f71f73b3259769a336728629017d600
