### ISSUE TITLE
Add Button to go back to values for Germany (total)

### ISSUE THREAD

**Issue by NXXR** [DLR-SC/ESID#98]
Add a button to the district map to select germany ('00000') as a district again, as currently the only way to select it is via the search bar.

- add [`chart.goHome()`](https://www.amcharts.com/docs/v5/charts/map-chart/map-pan-zoom/#Resetting_position_level) to reset the district map to its default view
- it may be possible to add a third button the the [Zoom Control Container](https://www.amcharts.com/docs/v5/reference/zoomcontrol/) to match the style and layout of the other zoom Buttons

**Comment by PawanKaur** [comment]
A reset button at search bar?

Currently search bar is not connected with the Map. Change in search bar is only reflected in line chart.
Ideally, the changes should be reflected in both map an line chart. Isnt it?

**Comment by NXXR** [comment]
https://gist.github.com/NXXR/5f71f73b3259769a336728629017d600

**Comment by hudaif747** [comment]
@NXXR There's a default [home button](https://www.amcharts.com/docs/v5/reference/zoomcontrol/#homeButton_property) setting for zoomControl for amcharts@5.7.5.

**Comment by NXXR** [comment]
> @hudaif747: @NXXR There's a default [home button](https://www.amcharts.com/docs/v5/reference/zoomcontrol/#homeButton_property) setting for zoomControl for amcharts@5.7.5.

Sweet.
I must've missed that in my search or they implemented it over from v4 after this issue was created 😁 
I'll test it some time soon and hopefully this issue is done in a line of code :D
